import { BellFilledSvg } from "./BellFilledSvg";
import { BellOutlinedSvg } from "./BellOutlinedSvg";
import { BookSvg } from "./BookSvg";
import { ChevronSvg } from "./ChevronSvg";
import { CircledArrowSvg } from "./CircledArrowSvg";
import { CrossSvg } from "./CrossSvg";
import { DownRoundedTriangleSvg } from "./DownRoundedTriangleSvg";
import { FileSvg } from "./FileSvg";
import { FourSquaresSvg } from "./FourSquaresSvg";
import { GearSvg } from "./GearSvg";
import { HomeSvg } from "./HomeSvg";
import { IconAdapter } from "./IconAdapter";
import { LogoutSvg } from "./LogoutSvg";
import { MeditatingPersonSvg } from "./MeditatingPersonSvg";
import { PapAIFaceSvg } from "./PapAIFaceSvg";
import { PenSvg } from "./PenSvg";
import { ThreeHorizontalStrokesSvg } from "./ThreeHorizontalStrokesSvg";
import { TwoHorizontalLinesSvg } from "./TwoHorizontalLinesSvg";
import { UserSvg } from "./UserSvg";

// export with IconAdapter applied
export const BellFilledIcon = IconAdapter(BellFilledSvg);
export const BellOutlinedIcon = IconAdapter(BellOutlinedSvg);
export const BookIcon = IconAdapter(BookSvg);
export const ChevronIcon = IconAdapter(ChevronSvg);
export const CircledArrowIcon = IconAdapter(CircledArrowSvg);
export const CrossIcon = IconAdapter(CrossSvg);
export const DownRoundedTriangleIcon = IconAdapter(DownRoundedTriangleSvg);
export const FileIcon = IconAdapter(FileSvg);
export const FourSquaresIcon = IconAdapter(FourSquaresSvg);
export const GearIcon = IconAdapter(GearSvg);
export const HomeIcon = IconAdapter(HomeSvg);
export const LogoutIcon = IconAdapter(LogoutSvg);
export const MeditatingPersonIcon = IconAdapter(MeditatingPersonSvg);
export const PapAIFaceIcon = IconAdapter(PapAIFaceSvg);
export const PenIcon = IconAdapter(PenSvg);
export const ThreeHorizontalStrokesIcon = IconAdapter(ThreeHorizontalStrokesSvg);
export const TwoHorizontalLinesIcon = IconAdapter(TwoHorizontalLinesSvg);
export const UserIcon = IconAdapter(UserSvg);

